The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.
Broadcasting provides a means of vectorizing array operations.

In [1]:
import numpy as np 

A = np.array([5, 7, 3, 1]) 
B = np.array([90, 50, 0, 30]) 

# array are compatible because of same Dimension 
c = A * B
print (c) 

[450 350   0  30]


Let’s assume that we have a large data set, each datum is a list of parameters. In Numpy we have a 2-D array, where each row is a datum and the number of rows is the size of the data set. Suppose we want to apply some sort of scaling to all these data every parameter gets its own scaling factor or say Every parameter is multiplied by some factor.

#### Let’s see a naive way of producing this computation with Numpy:

In [5]:
import numpy as np

macros = np.array([ 
[0.8, 2.9, 3.9], 
[52.4, 23.6, 36.5], 
[55.2, 31.7, 23.9], 
[14.4, 11, 4.9] 
]) 

macros

array([[ 0.8,  2.9,  3.9],
       [52.4, 23.6, 36.5],
       [55.2, 31.7, 23.9],
       [14.4, 11. ,  4.9]])

In [4]:
# Create a new array filled with zeros, 
# of the same shape as macros. 
result = np.zeros_like(macros) 
result

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
macros

array([[ 0.8,  2.9,  3.9],
       [52.4, 23.6, 36.5],
       [55.2, 31.7, 23.9],
       [14.4, 11. ,  4.9]])

In [6]:
cal_per_macro = np.array([3, 3, 8]) 

# Now multiply each row of macros by 
# cal_per_macro. In Numpy, `*` is 
# element-wise multiplication between two arrays. 
for i in range(macros.shape[0]): 
    result[i, :] = macros[i, :] * cal_per_macro 

result 

array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

#### Rank of an Array
In computer programming, rank with no further specifications is usually a synonym for (or refers to) "number of dimensions"; thus, a two-dimensional array has rank two, a three-dimensional array has rank three and so on.

#### Broadcasting Rules:

Broadcasting two arrays together follow these rules:

1. If the arrays don't have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together iff they are compatible with all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

In [8]:
import numpy as np 
a = np.array([17, 11, 19]) # 1x3 Dimension array 
print(a) 
b = 3
print(b) 

# Broadcasting happened beacuse of 
# miss match in array Dimension. 
c = a + b 
print(c) 

[17 11 19]
3
[20 14 22]


In [9]:
import numpy as np 
A = np.array([[11, 22, 33], [10, 20, 30]]) 
print(A) 

b = 4
print(b) 

C = A + b 
print(C) 

[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


In [10]:
import numpy as np 

v = np.array([12, 24, 36]) 
w = np.array([45, 55])

v.shape, w.shape

((3,), (2,))

In [13]:
v

array([12, 24, 36])

In [15]:
np.reshape(v, (3, 1)), w

(array([[12],
        [24],
        [36]]), array([45, 55]))

In [11]:
# To compute an outer product we first 
# reshape v to a column vector of shape 3x1 
# then broadcast it against w to yield an output 
# of shape 3x2 which is the outer product of v and w 
print(np.reshape(v, (3, 1)) * w) 

[[ 540  660]
 [1080 1320]
 [1620 1980]]


In [16]:
v

array([12, 24, 36])

In [17]:
X = np.array([[12, 22, 33], [45, 55, 66]]) 

# x has shape 2x3 and v has shape (3, ) 
# so they broadcast to 2x3, 
print(X + v) 

[[ 24  46  69]
 [ 57  79 102]]


In [25]:
X.T

array([[12, 45],
       [22, 55],
       [33, 66]])

In [23]:
w

array([45, 55])

In [28]:
(X.T + w).T

array([[ 57,  67,  78],
       [100, 110, 121]])

In [29]:
# Add a vector to each column of a matrix X has 
# shape 2x3 and w has shape (2, ) If we transpose X 
# then it has shape 3x2 and can be broadcast against w 
# to yield a result of shape 3x2. 

# Transposing this yields the final result 
# of shape 2x3 which is the matrix. 
print((X.T + w).T) 

[[ 57  67  78]
 [100 110 121]]


In [33]:
X

array([[12, 22, 33],
       [45, 55, 66]])

In [39]:
np.reshape(w, (2,1))

array([[45],
       [55]])

In [37]:
X + np.reshape(w, (2,1))

array([[ 57,  67,  78],
       [100, 110, 121]])

In [40]:
# Another solution is to reshape w to be a column 
# vector of shape 2X1 we can then broadcast it 
# directly against X to produce the same output. 
print(X + np.reshape(w, (2, 1)))

[[ 57  67  78]
 [100 110 121]]


In [41]:
X

array([[12, 22, 33],
       [45, 55, 66]])

In [42]:
# Multiply a matrix by a constant, X has shape 2x3. 
# Numpy treats scalars as arrays of shape(); 
# these can be broadcast together to shape 2x3. 
print(X * 2)

[[ 24  44  66]
 [ 90 110 132]]


#### Plotting a two-dimensional function -

Broadcasting is also frequently used in displaying images based on two-dimensional functions. If we want to define a function z=f(x, y).

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 

# Computes x and y coordinates for 
# points on sine and cosine curves 
x = np.arange(0, 3 * np.pi, 0.1) 
y_sin = np.sin(x) 
y_cos = np.cos(x) 

# Plot the points using matplotlib 
plt.plot(x, y_sin) 
plt.plot(x, y_cos) 
plt.xlabel('x axis label') 
plt.ylabel('y axis label') 
plt.title('Sine and Cosine') 
plt.legend(['Sine', 'Cosine']) 

plt.show() 